[renderer]
samples = 100
integrator = "pt-explicit"
accel = "linear"
polygon-accel = "bvh"

[sampler]
type = "mt"

[film]
resolution = [512, 512]

[sky]
type = "uniform"
color = [0.0, 0.0, 0.0]
path = "PaperMill_E_3k.hdr"
intensity = 1.0
phi-offset = 3.14
theta-offset = 0


[camera]
type = "thin-lens"
lens-distance = 1.0
focus-point = [0.0, 1.0, 0.0]
f-number = 3.5
[camera.transform]
type = "look-at"
origin = [0.0, 0, -3.8]
target = [0.0, 0, 0.0]


[[texture]]
name = "white"
type = "uniform"
color = [0.9, 0.9, 0.9]
[[texture]]
name = "red"
type = "uniform"
color = [0.8, 0.2, 0.2]
[[texture]]
name = "green"
type = "uniform"
color = [0.2, 0.8, 0.2]
[[texture]]
name = "blue"
type = "uniform"
color = [0.2, 0.2, 0.8]
[[texture]]
name = "uv"
type = "image"
path = "uv_test.png"
[[texture]]
name = "earth"
type = "image"
path = "earth2.jpg"


[[material]]
name = "white"
type = "oren-nayar"
sigma = 0.3
albedo = "white"

[[material]]
name = "uv"
type = "oren-nayar"
sigma = 0.3
albedo = "uv"

[[material]]
name = "red"
type = "oren-nayar"
sigma = 0.3
albedo = "red"

[[material]]
name = "green"
type = "oren-nayar"
sigma = 0.3
albedo = "green"

[[material]]
name = "blue"
type = "oren-nayar"
sigma = 0.3
albedo = "blue"

[[material]]
name = "mirror"
type = "mirror"
albedo = "white"

[[material]]
name = "glass"
type = "glass"
ior = 1.5
albedo = "white"

[[material]]
name = "glass2"
type = "glass"
ior = 1.5
albedo = "uv"

[[material]]
name = "beckmann"
type = "beckmann"
albedo = "white"
roughness = 0.4
ior = 8.0

[[material]]
name = "ggx"
type = "ggx"
albedo = "white"
roughness = 0.4
ior = 8.0

[[material]]
name = "plastic"
type = "plastic"
albedo = "white"
ior = 1.5

[[material]]
name = "earth"
type = "plastic"
albedo = "earth"
ior = 1.6


[[mesh]]
name = "bigSphere"
type = "sphere"
radius = 10000.0

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0

[[mesh]]
name = "light"
type = "sphere"
radius = 1.0

[[mesh]]
name = "dragon"
type = "obj"
path = "dragon.obj"


[[object]]
name = "floor"
mesh = "bigSphere"
material = "blue"
[[object.transform]]
type = "translate"
vector = [0, -10001, 0]

[[object]]
name = "dragon"
mesh = "dragon"
material = "ggx"
[[object.transform]]
type = "translate"
vector = [0.0, -1.0, 0.0]
[[object.transform]]
type = "scale"
vector = [0.2, 0.2, 0.2]

[[object]]
name = "light"
mesh = "light"
material = "white"
[[object.transform]]
type = "translate"
vector = [0, 5, 0]


[[light]]
type = "area"
object = "light"
emission = [70.0, 70.0, 70.0]
