[renderer]
samples = 100
integrator = "pt"

[sampler]
type = "mt"

[film]
resolution = [512, 512]

[sky]
type = "ibl"
color = [1.0, 1.0, 1.0]
path = "PaperMill_E_3k.hdr"
intensity = 1.0
phi-offset = 3.14
theta-offset = 0


[camera]
type = "thin-lens"
lens-distance = 1.0
focus-point = [1.5, 0.0, 2.0]
f-number = 3.5
[camera.transform]
type = "look-at"
origin = [0.0, 1.0, -3.0]
target = [0.0, 1.0, 5.0]


[[texture]]
name = "texture"
type = "uniform"
color = [0.9, 0.9, 0.9]
[[texture]]
name = "uv"
type = "image"
path = "uv_test.png"


[[material]]
name = "white"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "uv"
type = "oren-nayar"
sigma = 0.3
albedo = "uv"

[[material]]
name = "red"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "green"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "blue"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "mirror"
type = "mirror"
albedo = "texture"

[[material]]
name = "glass"
type = "glass"
ior = 1.5
albedo = "texture"

[[material]]
name = "beckmann"
type = "beckmann"
albedo = "texture"
roughness = 0.4
ior = 8.0

[[material]]
name = "ggx"
type = "ggx"
albedo = "texture"
roughness = 0.4
ior = 8.0

[[material]]
name = "plastic"
type = "plastic"
albedo = "uv"
ior = 1.5


[[mesh]]
name = "bigSphere"
type = "sphere"
radius = 10000.0

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0

[[mesh]]
name = "light"
type = "sphere"
radius = 0.2

[[object]]
name = "floor"
mesh = "bigSphere"
material = "white"
[[object.transform]]
type = "translate"
vector = [0, -10001, 0]

[[object]]
name = "left_ball"
mesh = "sphere"
material = "glass"
[[object.transform]]
type = "translate"
vector = [-1.5, 0.0, 3.0]

[[object]]
name = "right_ball"
mesh = "sphere"
material = "plastic"
[[object.transform]]
type = "translate"
vector = [1.5, 0, 2]
