[renderer]
samples = 100
integrator = "pt"

[sampler]
type = "mt"

[film]
resolution = [512, 512]

[sky]
type = "ibl"
path = "PaperMill_E_3k.hdr"
intensity = 1.0
phi-offset = 0
theta-offset = 0


[camera]
type = "thin-lens"
lens-distance = 1.0
focus-point = [0.0, 0.0, 2.5]
f-number = 5.6
[camera.transform]
type = "look-at"
origin = [0.0, 1.0, -3.0]
target = [0.0, 1.0, 5.0]


[[material]]
name = "white"
type = "oren-nayar"
sigma = 0.3
albedo = [0.9, 0.9, 0.9]

[[material]]
name = "red"
type = "oren-nayar"
sigma = 0.3
albedo = [0.8, 0.2, 0.2]

[[material]]
name = "green"
type = "oren-nayar"
sigma = 0.3
albedo = [0.2, 0.8, 0.2]

[[material]]
name = "blue"
type = "oren-nayar"
sigma = 0.3
albedo = [0.2, 0.2, 0.8]

[[material]]
name = "mirror"
type = "mirror"
albedo = [0.9, 0.9, 0.9]

[[material]]
name = "beckmann"
type = "beckmann"
albedo = [1.0, 1.0, 1.0]
roughness = 0.4
ior = 8.0

[[material]]
name = "ggx"
type = "ggx"
albedo = [1.0, 1.0, 1.0]
roughness = 0.4
ior = 8.0


[[mesh]]
name = "bigSphere"
type = "sphere"
radius = 10000.0

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0

[[mesh]]
name = "light"
type = "sphere"
radius = 0.2


[[object]]
name = "floor"
mesh = "bigSphere"
material = "ggx"
[[object.transform]]
type = "translate"
vector = [0, -10001, 0]

[[object]]
name = "left_ball"
mesh = "sphere"
material = "green"
[[object.transform]]
type = "translate"
vector = [-1.5, 0.0, 3.0]

[[object]]
name = "right_ball"
mesh = "sphere"
material = "blue"
[[object.transform]]
type = "translate"
vector = [1.5, 0, 2]
