[renderer]
samples = 36
integrator = "debug-normal"
accel = "bvh"
polygon-accel = "bvh"

[sampler]
type = "mt"

[filter]
type = "box"
radius = [0.499, 0.499]

[film]
resolution = [512, 512]

[sky]
type = "uniform"
color = [0.0, 0.0, 0.0]
path = "PaperMill_E_3k.hdr"
intensity = 1.0
phi-offset = 3.14
theta-offset = 0


[camera]
type = "ideal-pinhole"
lens-distance = 1.0
focus-point = [0.0, 1.0, 0.0]
f-number = 22.0
[camera.transform]
type = "look-at"
origin = [0.0, 1.0, -2.0]
target = [0.0, 1.0, 0.0]


[[texture]]
name = "texture"
type = "uniform"
color = [0.9, 0.9, 0.9]


[[material]]
name = "white"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"


[[mesh]]
name = "bunny"
type = "obj"
path = "bunny.obj"

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0


[[object]]
name = "bunny"
mesh = "bunny"
material = "white"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]

[[object]]
name = "sphere"
mesh = "sphere"
material = "white"
[[object.transform]]
type = "translate"
vector = [0.0, 10.0, 0.0]

[[light]]
type = "area"
object = "sphere"
emission = [10.0, 10.0, 10.0]
