[renderer]
samples = 16
integrator = "debug-uv"
accel = "bvh"
polygon-accel = "bvh"

[sampler]
type = "mt"

[filter]
type = "triangle"
radius = [0.499, 0.499]

[film]
resolution = [512, 512]

[sky]
type = "uniform"
color = [1.0, 1.0, 1.0]
path = "HDR_040_Field_Ref.hdr"
intensity = 1.0
phi-offset = 3.14
theta-offset = 0


[camera]
type = "ideal-pinhole"
lens-distance = 1.0
focus-point = [0.0, 1.0, 0.0]
f-number = 22.0
[camera.transform]
type = "look-at"
origin = [0.0, 10, 0.0]
target = [-1.0, 10, 0.0]


[[texture]]
name = "texture"
type = "uniform"
color = [0.9, 0.9, 0.9]
[[texture]]
name = "black"
type = "uniform"
color = [0.2, 0.2, 0.2]
[[texture]]
name= "check"
type = "checkerboard"
odd = "texture"
even = "black"
alphaX = 1.0
alphaY = 1.0
alphaZ = 1.0


[[material]]
name = "white"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "check"
type = "lambert"
albedo = "check"


[[mesh]]
name = "sponza"
type = "obj"
path = "sponza.obj"


[[object]]
name = "sponza"
mesh = "sponza"
material = "white"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]
