[renderer]
samples = 100
integrator = "pt"
accel = "bvh"
polygon-accel = "bvh"

[sampler]
type = "mt"

[filter]
type = "triangle"
radius = [0.5, 0.5]

[film]
resolution = [512, 512]

[sky]
type = "uniform"
color = [1.0, 1.0, 1.0]
path = "PaperMill_E_3k.hdr"
intensity = 1.0
phi-offset = 0.0
theta-offset = 0


[camera]
type = "ideal-pinhole"
lens-distance = 1.0
focus-point = [1.5, 0.0, 2.0]
f-number = 3.5
[camera.transform]
type = "look-at"
origin = [0.0, 0.0, -3.0]
target = [0.0, 0.0, 0.0]


[[texture]]
name = "texture"
type = "uniform"
color = [0.9, 0.9, 0.9]
[[texture]]
name = "black"
type = "uniform"
color = [0.2, 0.2, 0.2]
[[texture]]
name= "check"
type = "checkerboard"
odd = "texture"
even = "black"
alphaX = 1.0
alphaY = 1.0
alphaZ = 1.0
[[texture]]
name = "uv"
type = "image"
path = "uv_test.png"
[[texture]]
name = "earth"
type = "image"
path = "earth2.jpg"


[[material]]
name = "white"
type = "oren-nayar"
sigma = 0.3
albedo = "check"

[[material]]
name = "uv"
type = "oren-nayar"
sigma = 0.3
albedo = "uv"

[[material]]
name = "red"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "green"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "blue"
type = "oren-nayar"
sigma = 0.3
albedo = "texture"

[[material]]
name = "mirror"
type = "mirror"
albedo = "texture"

[[material]]
name = "glass"
type = "glass"
ior = 1.5
albedo = "texture"

[[material]]
name = "glass2"
type = "glass"
ior = 1.5
albedo = "uv"

[[material]]
name = "beckmann"
type = "beckmann"
albedo = "texture"
roughness = 0.4
ior = 8.0

[[material]]
name = "ggx"
type = "ggx"
albedo = "texture"
roughness = 0.4
ior = 8.0

[[material]]
name = "plastic"
type = "plastic"
albedo = "texture"
ior = 1.5

[[material]]
name = "earth"
type = "plastic"
albedo = "earth"
ior = 1.6

[[material]]
name = "check"
type = "lambert"
albedo = "check"


[[mesh]]
name = "bigSphere"
type = "sphere"
radius = 1000.0

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0

[[mesh]]
name = "light"
type = "sphere"
radius = 0.2

[[mesh]]
name = "dragon"
type = "obj"
path = "dragon.obj"


[[object]]
name = "floor"
mesh = "bigSphere"
material = "check"
[[object.transform]]
type = "translate"
vector = [0, -1001, 0]

[[object]]
name = "left_ball"
mesh = "sphere"
material = "earth"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]
